# http receiver only
unset KAFKA_BOOTSTRAP_SERVERS
unset REDIS_ADDRESS
unset HTTP_PORT


unset KAFKA_BOOTSTRAP_SERVERS
unset KAFKA_TOPIC
unset KAFKA_GROUP
unset KAFKA_NET_TLS_ENABLE
unset KAFKA_NET_SASL_ENABLE
unset KAFKA_NET_SASL_USER
unset KAFKA_NET_SASL_PASSWORD
