apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-es100
  annotations:
    autoscaling.knative.dev/class: keda.autoscaling.knative.dev
    autoscaling.knative.dev/minScale: "20"
    autoscaling.knative.dev/maxScale: "20"
    keda.autoscaling.knative.dev/pollingInterval: "1"
    keda.autoscaling.knative.dev/cooldownPeriod: "30"
    keda.autoscaling.knative.dev/kafkaLagThreshold: "10"
spec:
  consumerGroup: kafkaes100j27g
  bootstrapServers:
  - kafka-1.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093
  topics:
  - e2et100
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-secret-es
          key: user
      password:
        secretKeyRef:
          name: kafka-secret-es
          key: password 
    tls:
      enable: true
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cloudevents-forwarder-ksvc
